package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"fmt"

	"github.com/slaff-bg/stockroom/ports/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, userID string, input model.UserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var users []*model.User
	dbg := r.GDB.WithContext(ctx).Find(&users)
	if err := dbg.Error; err != nil {
		return nil, err
	}
	return users, nil
}

// UserByID is the resolver for the UserById field.
func (r *queryResolver) UserByID(ctx context.Context, id *string) (*model.User, error) {
	var u model.User
	dbg := r.GDB.WithContext(ctx).Where("id = ?", id).First(&u)
	if err := dbg.Error; err != nil {
		return nil, err
	}
	return &u, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) GetOneUser(ctx context.Context, id *string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetOneUser - GetOneUser"))
}
func (r *queryResolver) UserById(ctx context.Context, id *string) (*model.User, error) {
	var u model.User
	dbg := r.GDB.WithContext(ctx).Where("id = ?", id).First(&u)
	if err := dbg.Error; err != nil {
		return nil, err
	}
	return &u, nil
}
